site_name: JRbot/LetheBot 使用帮助
nav:
- '主页': index.md
- '快速使用': tutorial.md
- '群内使用':
    - '欢迎语': 'interact-with-group-msg/welcome-msg.md'
    - '触发词': 'interact-with-group-msg/triggers.md'
    - '退群“感言”': 'interact-with-group-msg/exit-msg.md'
    - '可用模块': 'available-modules/index.md'
- '私聊使用':
    - '问题反馈': 'communicate-with-private-msg/bug-reporting.md'
- '使用管理功能':
    - '主页': 'manage-group-with-bot/index.md'
    - '禁言与解禁': 'manage-group-with-bot/ban-and-unban.md'
    - '撤回消息': 'manage-group-with-bot/revoke-msg.md'
    - '管理模块': 'manage-group-with-bot/managing-modules.md'
- '个人音游自制谱下载': 'available-modules/get_personal_maps.md'
- '常见问题Q&A': qa.md
- '使用协议': agreement.md

theme:
  name: material
  icon: 
    logo: material/cloud
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - header.autohide
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  language: 'zh'
  palette: 
    scheme: 'preference'
    primary: 'deep orange'
    accent: 'amber'
extra_css: ['css/bot.css']

copyright: copyright &copy; Jason Ren 2019-2021 (<a href="https://www.fantasyroom.cn" target="_blank">fantasyroom.cn</a>) . All rights reserved
repo_url: https://github.com/jasonren0403/jrbot-docs
repo_name: jrbot-docs
edit_uri: edit/main/docs
site_description: 'JRbot/LetheBot help document'
site_author: 'Jason'
use_directory_urls: true
docs_dir: 'docs_markdown'
site_dir: 'docs'
extra:
  disqus: 'something'
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jasonren0403
    - icon: fontawesome/brands/qq
      link: http://wpa.qq.com/msgrd?v=3&uin=727847763&site=qq&menu=yes
    - icon: fontawesome/brands/discord
      link: https://discord.gg/s33UBWEPxb
      name: Join to my discussion(and try using my discord bot<developing state>!)
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - jp
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
      enable_creation_date: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - toc:
      permalink: true
  - footnotes
  - meta
  - attr_list
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.tilde
